# Defines a default set of lint rules enforced for
# projects at Google. For details and rationale,
# see https://github.com/dart-lang/pedantic#enabled-lints.
include: package:lint/analysis_options_package.yaml

# For lint rules and documentation, see http://dart-lang.github.io/linter/lints.
# Uncomment to specify additional rules.
linter:
#   rules:
#     - camel_case_types

analyzer:
  errors:
    # Used to construct Logger.
    # Should not matter in performance for the low usage (fingers crossed).
    no_runtimetype_tostring: ignore
#   exclude:
#     - path/to/excluded/files/**
